---
# title: "App instructions"
# author: "Gopal Penny"
# date: "1/12/2020"
output: html_document
---

## A simple model for groundwater behavior

<iframe width="560" height="315" src="https://www.youtube.com/embed/XnmbmAbx3HM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### What anem-app does

This web application models 2D, steady-state groundwater behavior in *simple* aquifers purturbed by pumping wells -- note the emphasis on simple. The model requires aquifer boundaries to be rectangular and have uniform saturated hydraulic conductivity. It works for confined and unconfined aquifers, any number of pumping wells, and can track any number of particles in the aquifer. Boundaries can be "no flow" (e.g., due to an impervious layer), "constant head" (e.g., a river), or "open" (i.e., there is no boundary at the edge of the simulation). 

The app is best used to develop an intuition for groundwater behavior in a wide variety of situations. However, given the idealized features of the app and simplified representation of boundaries, it is unable to reproduce peculiarities of any given groundwater system such as 3-dimensional flow, transient flow, irregular aquifer geometries, or non-uniform hydraulic conductivity. For these reasons, this app is ideal as a starting point for groundwater modeling but unlikely to be as accurate as models that allow for more complex processes and parameterization.

The tool is based on the [analytical element method](https://en.wikipedia.org/wiki/Analytic_element_method) for groundwater models. More specifically, it utilizes the method of images, in which boundary behavior reproduced by mirroring wells across the boundaries. This approach is documented in a number of sources (e.g., Strack, 2017). The code underlying the model is contained within the `anem` R package, currently in development and accessible via [github](https://github.com/gopalpenny/anem).

Please note that this app, as hosted by [shinyapps.io](https://www.shinyapps.io/), may timeout due to inactivity, excessive memory usage, or other unforseen issues. For this reason it is recommended that you backup your work regularly using the "File" -> "Download scenario" button.

Please submit feedback (bugs, etc.) or feature requests on [github](https://github.com/gopalpenny/anem/issues).

Strack, Otto DL. *Analytical groundwater mechanics.* Cambridge University Press, 2017.

### Groundwater concepts

If you are unfamiliar with groundwater or groundwater flow, the following resources may be a good starting point to learn the basics concepts behind the application:

* [Aquifers and groundwater](https://www.usgs.gov/special-topic/water-science-school/science/aquifers-and-groundwater?qt-science_center_objects=0#qt-science_center_objects) - Introductory information from USGS 
* [Groundwater flow](https://opentextbc.ca/physicalgeology2ed/chapter/14-2-groundwater-flow/) - Section 14.2, Physical Geography Ed. 2, from B.C. Campus

The groundwater model behind the application has been described in [Penny *et al.* (2018)](https://ngwa.onlinelibrary.wiley.com/journal/17456584) in *Groundwater*.

### Use notes for anem-app

#### Prepare scenario

1. Define aquifer
    + *Define boundaries*. The aquifer boundary serves as the domain boundary. With the approach used in this app, the aquifer **must** be rectangular. 
        + Boundary vertices. Define boundaries by clicking 4 points on the map. The points must be clicked sequentially, following the boundaries of the rectangle. The app will "rectangularize" the boundaries to ensure right angles at the corners.
        + Boundary types. Boundaries can be set as "no flow" or "constant head".
    + *Define properties*.
        + Porosity, n
        + Saturated hydraulic conductivity, Ksat
        + Undisturbed head (for unconfined aquifers, this is the thickness of the water table without pumping)
        + Aquifer thickness (confined aquifers only)
    + *Define recharge.
        + Click 2 points to set the direction of recharge. 
        + Recharge is specified as a constant background flow, in units of cumec (in direction of flow) / meter (perpendicular to flow).
        + Check "Enable recharge".
1. Define wells
    + *Set properties of new wells*:
        + Pumping rate, Q: specified as cubic meters per second. It should be negative for pumping (abstraction), and positive for injection.
        + Well diameter, diam (m): Diameter of the well.
        + Group and Weight are not currently used.
        + Radius of influence can be calculated for confined or unconfined aquifers, as defined in the *Radius of influence* tab. For confined aquifers using the Cooper and Jacobs (1946) approximation, "Storativity" is required. For unconfined aquifers using the Aravin and Numerov (1953) approximation, porosity is required. See [Fileccia, 2015](http://www.doi.org/10.7343/AS-117-15-0144) for further details.
    + *Add wells.* Click within the aquifer to add wells.
    + *Edit wells.* Any well property can be edited in the table below the map.
        + Clicking a well highlights that well within the table, and allows that well to be deleted.
1. Particle tracking
    + *Well capture zones*. Particle tracking can either be done by:
        1. reverse tracking particles from wells (select "Well capture zones"), or
        1. defining individual particles to track (deselect "Well capture zones")
    + *Max time.* Set the maximum time for determining particle trajectories.
    + *Add particles* (Individual particle tracking only). Click the map to set initial locations for individual particle tracking.
    + **NOTE:** Flow is non-reactive and non-dispersive. This means that travel times represent the "average" particle, but due to "dispersive" behavior of groundwater, some particles would arrive in less or more time. Furthermore, this analysis would underestimate the effect of macropores on travel times -- meaning transit times could be considerably lower!
1. Save or upload a scenario
    + The "File" panel allows you to save a scenario as an RDS file or upload a scenario that has been downloaded. The RDS file contains an R `list` object that contains the parameters and map clicks needed for the app. 
    + The R package `anem` (on [github](https://github.com/gopalpenny/anem)) has a helper function, `import_app_rds`, that imports the file and prepares it for simulation using the `anem` package.
        
#### View results

1. Explore the results 
    + You can by pan, zoom, or change the base map.
    + By default, the "Prepare" map and the "Results" map are linked, but can be unlinked with the checkbox.
1. Update the results
    + *Edit pumping.* You can edit the pumping rates of each well in the table to see how head within the aquifer and at each well changes.
    + *Update specific results.* You can update the results by clicking any of the checkboxes along the bottom. These are hierarchical: "Particle tracking" updates only itself, "Hyraulic head" updates the head and simulates "Particle tracking", and "Well images" updates all three.
