app <- ShinyDriver$new("../../")
app$snapshotInit("test_particles")

app$setInputs(maintabs = "prepare")
app$setInputs(b1_type = "CH")
app$setInputs(aquifermode = "properties")
app$setInputs(Ksat = 0.002)
app$setInputs(z0 = 5)
app$setInputs(aquifermode = "recharge")
app$setInputs(rechargeFlow = 0)
app$setInputs(rechargeFlow = 1e-05)
app$setInputs(rechargeFlow = 5e-06)
app$setInputs(enableRecharge = TRUE)
app$setInputs(usermode = "wells")
app$setInputs(Q = 0)
app$setInputs(Q = -0.5)
app$setInputs(usermode = "particles")
app$setInputs(max_tracking_time_years = 5)
app$setInputs(maintabs = "results")
app$snapshot()
