app <- ShinyDriver$new("../../")
app$snapshotInit("test_anem_app_prep")

app$setInputs(maintabs = "prepare")
app$setInputs(b1_type = "CH")
app$setInputs(b2_type = "CH")
app$setInputs(b4_type = "PB")
app$setInputs(aquifermode = "properties")
app$setInputs(porosity = 0.2)
app$setInputs(aquifer_type = "unconfined")
app$setInputs(Ksat = 5e-04)
app$setInputs(h0 = 0)
app$setInputs(h0 = 60)
app$setInputs(aquifermode = "recharge")
app$setInputs(enableRecharge = TRUE)
app$setInputs(rechargeFlow = 0)
app$setInputs(rechargeFlow = 5e-05)
app$setInputs(usermode = "wells")
app$setInputs(Q = -0.15)
app$setInputs(diam = 0)
app$setInputs(diam = 5)
app$setInputs(diam = 0.5)
app$setInputs(well_group = "B")
app$setInputs(welltab = "wellROI")
app$setInputs(pumpingtime_months = 120)
app$setInputs(welltab = "newwell")
app$setInputs(well_group = "C")
app$snapshot()
