app <- ShinyDriver$new("../../")
app$snapshotInit("test_anem_app_well_capture")

app$setInputs(maintabs = "prepare")
app$setInputs(aquifermode = "properties")
app$setInputs(z0 = character(0))
app$setInputs(z0 = 5)
app$setInputs(aquifermode = "recharge")
app$setInputs(rechargeFlow = 0)
app$setInputs(rechargeFlow = 1e-05)
app$setInputs(enableRecharge = TRUE)
app$setInputs(usermode = "wells")
app$setInputs(Q = -0.3)
app$setInputs(usermode = "particles")
app$setInputs(captureParticles = 5)
app$setInputs(captureParticles = 4)
app$setInputs(max_tracking_time_years = character(0))
app$setInputs(max_tracking_time_years = 5)
app$setInputs(wellCapture = TRUE)
app$setInputs(maintabs = "results")
app$snapshot()
