---
# title: "App instructions"
# author: "Gopal Penny"
# date: "1/12/2020"
output: html_document
---

## A simple model for groundwater behavior

### What anem-app does

This shiny application is currently in development. It functions when used according to the instructions provided below.

This web application models 2D, steady-state groundwater behavior in *simple* aquifers purturbed by pumping wells -- note the emphasis on simple. The model requires aquifer boundaries to be rectangular and have uniform, isotropic saturated hydraulic conductivity. It works for confined and unconfined aquifers, and any number of pumping wells. Boundaries can be "no flow" (e.g., due to an impervious layer) or "constant head (e.g., a river).

The tool is based on the [analytical element method](https://en.wikipedia.org/wiki/Analytic_element_method) for groundwater models. More specifically, it utilizes the method of images, in which boundary behavior reproduced by mirroring wells across the boundaries. This approach is documented in a number of sources (e.g., Strack, 2017). The code underlying the model is contained within the `anem` R package, currently in development and accessible via [github](https://github.com/gopalpenny/anem). Please submit feedback or feature requests to the [github issues](https://github.com/gopalpenny/anem/issues) tab.

Strack, Otto DL. *Analytical groundwater mechanics.* Cambridge University Press, 2017.

### Instructions

1. Define aquifer
    + *Define boundaries*. The aquifer boundary serves as the domain boundary. With the approach used in this app, the aquifer **must** be rectangular. Define boundaries by clicking 4 points on the map, and the app will "rectangularize" the boundaries.
    + *Define properties*. 
1. Define wells
    + *Set properties of new wells*:
        + Pumping rate, Q: specified as cubic meters per second. It should be negative for pumping (abstraction), and positive for injection.
        + Well diameter, diam (m): Diameter of the well.
        + Group and Weight are not currently used.
        + The radius of influence should be calculated.
    + *Add wells.* Click within the aquifer to add wells.
    + *Edit wells.* Any well property can be edited in the table.
        + Clicking a well highlights that well within the table, and allows that well to be deleted.
1. View results
    + *Edit pumping.* You can edit the pumping rates of each well to see how head within the aquifer and at each well changes.
